services:
  router1:
    build:
      dockerfile: netshoot-router
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      general-link:
      tunnel-2210:
        ipv6_address: 2001:200:0:1cdc:1e60::2210:3
      tunnel-2220:
        ipv6_address: 2001:200:0:1cdc:1e60::2220:3
  
  ping-container-general:
    build:
      dockerfile: netshoot-clients
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      general-link:
        ipv6_address: 2001:200:0:1cdc:1e60::2110:3

  ping-container-tunnel-2210:
    build:
      dockerfile: netshoot-clients

    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      tunnel-2210:
        ipv6_address: 2001:200:0:1cdc:1e60::2210:2

  ping-container-tunnel-2220:
    build:
      dockerfile: netshoot-clients
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      tunnel-2220:
        ipv6_address: 2001:200:0:1cdc:1e60::2220:2


networks:
  general-link:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:200:0:1cdc:1e60::2110:0/112
          ip_range: 2001:200:0:1cdc:1e60::2110:0/112
          gateway: 2001:200:0:1cdc:1e60::2110:1
    
  tunnel-2210:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:200:0:1cdc:1e60::2210:0/112
          ip_range: 2001:200:0:1cdc:1e60::2210:0/112
          gateway: 2001:200:0:1cdc:1e60::2210:1
  
  tunnel-2220:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:200:0:1cdc:1e60::2220:0/112
          ip_range: 2001:200:0:1cdc:1e60::2220:0/112
          gateway: 2001:200:0:1cdc:1e60::2220:1
