services:
  router1:
    image: netshoot_router:e60e256
    privileged: true
    cap_add:
      - NET_ADMIN
    command: /bin/sh -c "/app/network_config.sh; while true; do sleep 10000; done"
    networks:
      general-link:
      tunnel-2210:
        ipv4_address: 172.25.1.2
      tunnel-2220:
        ipv4_address: 172.26.1.2
  
  ping-container-general:
    image: netshoot:e60e256
    command: /bin/sh -c "while true; do sleep 10000; done"
    networks:
      general-link:
        ipv4_address: 172.27.100.3

  ping-container-tunnel-2210:
    image: netshoot:e60e256
    command: /bin/sh -c "while true; do sleep 10000; done"
    networks:
      tunnel-2210:
        ipv4_address: 172.25.1.3

  ping-container-tunnel-2220:
    image: netshoot:e60e256
    command: /bin/sh -c "while true; do sleep 10000; done"
    networks:
      tunnel-2220:
        ipv4_address: 172.26.1.3


networks:
  general-link:
    ipam:
      driver: default
      config:
        - subnet: 172.27.100.0/24
          ip_range: 172.27.100.0/24
          gateway: 172.27.100.254
    
  tunnel-2210:
    ipam:
      driver: default
      config:
        - subnet: 172.25.1.0/24
          ip_range: 172.25.1.0/24
          gateway: 172.25.1.254
  
  tunnel-2220:
    ipam:
      driver: default
      config:
        - subnet: 172.26.1.0/24
          ip_range: 172.26.1.0/24
          gateway: 172.26.1.254
